Use a wrapper to call yum once for each package
If installing multiple packages yum will return success if at least one package
installs, we want the build to fail if even a single package fails to install,
the simplest solution being to call yum once for each package.

diff --git a/docker-c6/Dockerfile b/docker-c6/Dockerfile
--- a/docker-c6/Dockerfile
+++ b/docker-c6/Dockerfile
@@ -1,43 +1,49 @@
 FROM centos:6
 
-RUN yum -y install yum-priorities
+# If installing multiple packages yum will return success if at least one package installs.
+# We don't want this, so we provide a wrapper to fail if *any* of the packages fail to install.
+RUN echo -e '#!/bin/bash\nfor p in "$@"; do\nyum -y install "$p" || exit 1; done' > /usr/local/sbin/yummy && \
+    chmod u+x /usr/local/sbin/yummy && \
+    cat /usr/local/sbin/yummy
 
-RUN yum -y install zip
+RUN yummy yum-priorities
+
+RUN yummy zip
 
 # CVMFS (for SUM tests only; install before adding other repos to ensure we have the latest version)
 # Install cvmfs-x509-helper for access to secure CVMFS repositories
-RUN yum -y install https://ecsft.cern.ch/dist/cvmfs/cvmfs-release/cvmfs-release-latest.noarch.rpm \
+RUN yummy https://ecsft.cern.ch/dist/cvmfs/cvmfs-release/cvmfs-release-latest.noarch.rpm \
                    https://ecsft.cern.ch/dist/cvmfs/cvmfs-config-egi/cvmfs-config-egi-2.0-1.el6.noarch.rpm  && \
-    yum -y install cvmfs-2.5.2-1.el6.x86_64 && \
-    yum -y install https://ecsft.cern.ch/dist/cvmfs/cvmfs-x509-helper/cvmfs-x509-helper-1.0-1.el6.x86_64.rpm
+    yummy cvmfs-2.5.2-1.el6.x86_64 && \
+    yummy https://ecsft.cern.ch/dist/cvmfs/cvmfs-x509-helper/cvmfs-x509-helper-1.0-1.el6.x86_64.rpm
 
 # EPEL
-RUN yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm
+RUN yummy https://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm
 
-# UMD
-RUN yum -y install http://repository.egi.eu/sw/production/umd/4/sl6/x86_64/updates/umd-release-4.1.3-1.el6.noarch.rpm
+# Unified Middleware distribution
+RUN yummy http://repository.egi.eu/sw/production/umd/4/sl6/x86_64/updates/umd-release-4.1.3-1.el6.noarch.rpm
 
 # Basic dependencies
-RUN yum -y install freetype expat gcc glibc-headers compat-expat1 compat-openldap time man unzip quota attr tcsh
+RUN yummy freetype expat gcc glibc-headers compat-expat1 compat-openldap time man unzip quota attr tcsh
 
 # Install HEP_OSlibs
-RUN yum -y install http://linuxsoft.cern.ch/wlcg/sl6/x86_64/HEP_OSlibs_SL6-1.1.5-1.el6.x86_64.rpm
+RUN yummy http://linuxsoft.cern.ch/wlcg/sl6/x86_64/HEP_OSlibs_SL6-1.1.5-1.el6.x86_64.rpm
 
 # Install glexec, lcmaps & lcas
-RUN yum -y install glexec mkgltempdir \
+RUN yummy glexec mkgltempdir \
                    lcmaps lcmaps-plugins-verify-proxy lcmaps-plugins-basic lcmaps-plugins-voms lcmaps-plugins-c-pep \
                    lcas lcas-plugins-basic lcas-plugins-voms
 
 # Machine job features
-RUN yum -y install http://quattor.web.lal.in2p3.fr/packages/machine-job-features/sl6/noarch/mjf-htcondor-00.19-1.noarch.rpm
+RUN yummy http://quattor.web.lal.in2p3.fr/packages/machine-job-features/sl6/noarch/mjf-htcondor-00.19-1.noarch.rpm
 
-# Boost
-RUN yum -y install boost-date-time boost-filesystem boost-graph boost-iostreams boost-program-options \
+# Boost (need to ensure gfal CLI from CVMFS will work for some VOs)
+RUN yummy boost-date-time boost-filesystem boost-graph boost-iostreams boost-program-options \
                    boost-python boost-regex boost-serialization boost-signals boost-system boost-test \
                    boost-thread boost-wave
 
 # Singularity
-RUN yum -y install singularity-2.6.1-1.1.el6.x86_64 \
+RUN yummy singularity-2.6.1-1.1.el6.x86_64 \
                    singularity-runtime-2.6.1-1.1.el6.x86_64
 
 # Disable overlay and loop device management in singularity
